### ISSUE TITLE
Usage as library to include in a project

### ISSUE THREAD

**Issue by Mayeu** [mmgen/mmgen#1]
Hello,

Is there a supported way to use this project has a library? I would like to include key generation & transaction support for multiple cryptocurrencies in a project, and the quantity of altcoins supported by mmgen make it a pretty solid choice.

Thank for your answer.

**Comment by mmgen** [comment]
Yes, you can install MMGen and then import individual modules into your project, why not? In particular, altcoin.py lends itself to this. Bear in mind that support for most altcoins is experimental: the trust level for each coin is indicated in the coin_constants list. If you'd like to test, update and expand the list, I'd be most grateful for your help. I've been unable to locate an authoritative source for altcoin constants on the net. Perhaps this could be it.

MMGen can generate keys and addresses for all coins in the list, but tx support (which really means full wallet support) is limited to BTC, BCH and LTC at the moment. I've thought of adding ETH wallet support via geth, but this would require some work.
