### ISSUE TITLE
error when trying to show hash presets

### ISSUE THREAD

**Issue by dooglus** [mmgen/mmgen#3]
I'm working through the [getting started page](https://github.com/mmgen/mmgen/wiki/Getting-Started-with-MMGen). While creating my first wallet it asked me what 'hash preset' I wanted. I had no idea what that meant, so I ran `mmgen-walletgen -h` and saw:

    -z, --show-hash-presets Show information on available hash presets

I ran `mmgen-walletgen -z` and got the following error:

    $ mmgen-walletgen -z
    Available parameters for scrypt.hash():
      Preset  N      r    p

    MMGen Unhandled Exception (IndexError): tuple index out of range
    $ 

Using the default value of 3 let me generate a wallet, but I'd like to understand what that means.

I'm not familiar with Python3's str.format(), but this appears to fix the issue:

    diff --git a/mmgen/opts.py b/mmgen/opts.py
    index 65216e0..1696575 100755
    --- a/mmgen/opts.py
    +++ b/mmgen/opts.py
    @@ -42,7 +42,7 @@ def _show_hash_presets():
     	msg('Available parameters for scrypt.hash():')
     	msg(fs.format('Preset','N','r','p'))
     	for i in sorted(g.hash_presets.keys()):
    -		msg(fs.format("'{}'".format(i,*g.hash_presets[i])))
    +		msg(fs.format(i,*g.hash_presets[i]))
     	msg('N = memory usage (power of two), p = iterations (rounds)')
     
     def opt_preproc_debug(short_opts,long_opts,skipped_opts,uopts,args):

**Comment by mmgen** [comment]
Thanks much!  I've added your patch to today's upcoming subrelease. This was a regression that crept in with commit 351f5f9 and has been lurking undetected ever since. These info options really need to be added to the test suite to avoid annoying errors like this.
