### ISSUE TITLE
support bitcoind with multiple wallets

### ISSUE THREAD

**Issue by camschaus** [mmgen/mmgen#9]
I have a few different wallets setup on my bitcoind node.  Unfortunately mmgen doesn't currently support a node with multiple wallets.

$ mmgen-addrimport --batch my.addrs 

MMGen Fatal Error (MMGenError):
ERROR: more than one Bitcoin Core wallet loaded: ['test', 'eps1', 'eps2']

**Comment by mmgen** [comment]
I'll consider supporting this. In the meantime, unloading the 3 loaded wallets with `bitcoin-cli unloadwallet` before running MMGen should do the trick. Then you can load them back again with `loadwallet`.

**Comment by camschaus** [comment]
Thanks.  I'll try unloading the other wallets I have loaded.

**Comment by mmgen** [comment]
> Thanks. I'll try unloading the other wallets I have loaded.

Issue resolved in commit b51868a. Enjoy!

**Comment by mmgen** [comment]
Issue fixed and closed
